services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    stdin_open: true
    tty: true
    networks:
      - app-network
    extra_hosts: 
      - "host.docker.internal:host-gateway"
networks:
  app-network: